In [ ]:
import numpy as np

In [ ]:
#1.check data type of arr
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
print(arr.dtype)

int64


In [ ]:
#2.
arr = np.array([1.5,2.6,3.7])
datatype = arr.dtype == 'float64'
print(datatype)



True


In [ ]:
#3.
complex_arr = np.array([1+2j,2+3j,4+3j],dtype = np.complex128)
complex_arr


array([1.+2.j, 2.+3.j, 4.+3.j])

In [ ]:
print(complex_arr.dtype)

complex128


In [ ]:
#4.
arr = np.array([1,2,3,4,5],dtype = np.float32)
print(arr.dtype)

float32


In [ ]:
#5.
arr = np.array([1.5,2.6,3.7])
print(arr.dtype)

float64


In [ ]:
# converting it to float32 to reduce decimal precision
arrfloat32 = np.array(arr,dtype = np.float32 )
print(arrfloat32.dtype)

float32


In [ ]:
#6.
def array_attribute(arr):
   print('array shape is: ', arr.shape)
   print('array size is: ', arr.size)
   print('array datatype is: ', arr.dtype)

In [ ]:
arr_ = np.array([1.3,1.4,5,3])
array_attribute(arr_)

array shape is:  (4,)
array size is:  4
array datatype is:  float64


In [ ]:
#7.
def check_dim(arr):
  return "dimension is:"+ str(arr.ndim)


In [ ]:
check_dim(np.array([[1,2,4,5,6],[4,5,6,7,8]]))

'dimension is:2'

In [ ]:
#8.
def item_size_info(arr_):
  print('item size is:', arr_.itemsize)
  print('total size in bytes is:', arr_.nbytes)

In [ ]:
item_size_info(np.array([1.5,2.6,3.7]))

item size is: 8
total size in bytes is: 24


In [ ]:
#9.
def array_strides(arr):
  print("strides is :" , arr.strides)

In [ ]:
array_strides(np.array([1.5,2.6,3.7]))

strides is : (8,)


In [ ]:
array_strides(np.array([[1,2,4,5,6],[4,5,6,7,8]]))

strides is : (40, 8)


In [ ]:
#10.
def shape_stride_array(arr):
  print("array shape is:" , arr.shape)
  print("array strides is :", arr.strides)



In [ ]:
shape_stride_array(np.array([[1,2,4,5,6],[4,5,6,7,8]]))

array shape is: (2, 5)
array strides is : (40, 8)


In [ ]:
#11.
def create_zeros_array(n):
  return np.zeros(n)

In [ ]:
create_zeros_array(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#12.
def create_ones_matrix(shape):
  return np.ones(shape)



In [ ]:
create_ones_matrix((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#13.
def generate_range_arr(start,stop,step):
  return np.arange(start,stop,step)


In [ ]:
generate_range_arr(1,15,3)

array([ 1,  4,  7, 10, 13])

In [ ]:
#14.
def generate_linear_space(start,stop,num):
  return np.linspace(start,stop,num)

In [ ]:
generate_linear_space(0.5,5.0,10)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
#15.
def create_identity_matrix(n):
  return np.eye(n,n)


In [ ]:
create_identity_matrix(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#16.
def list_to_array(lst):
  return np.array(lst)

In [ ]:
list_to_array([1,2,3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#17.
arr = np.array([1,2,3,4,4,5,6])
arr_view = arr.view()
arr_view

array([1, 2, 3, 4, 4, 5, 6])

In [ ]:
arr_view[0] = 10
arr_view

array([10,  2,  3,  4,  4,  5,  6])

In [ ]:
# modifying the arr_view also reflecting the original array
arr

array([10,  2,  3,  4,  4,  5,  6])

In [ ]:
#18.
def concatinate_arrays(arr1,arr2):
  return np.concatenate((arr1,arr2),axis = 1)


In [ ]:
concatinate_arrays((np.array([[1,2,3],[5,6,7]])),np.array([[4,5,6],[6,7,8]]))

array([[1, 2, 3, 4, 5, 6],
       [5, 6, 7, 6, 7, 8]])

In [ ]:
#19.
arr1 = np.array([[1,2,3],[3,4,2]])
arr2 = np.array([[4,5,6]])
np.concatenate((arr1,arr2),axis = 0)

array([[1, 2, 3],
       [3, 4, 2],
       [4, 5, 6]])

In [ ]:
#20.
def vstack_arrays(array_list):
  return np.vstack(array_list)


In [ ]:
arrays = np.array([1, 2,5]), np.array([3, 4, 5])
vstack_arrays(arrays)

array([[1, 2, 5],
       [3, 4, 5]])

In [ ]:
#21.
def array_with_step_size(start,stop,step):
  return np.arange(start,stop,step)

In [ ]:
array_with_step_size(1,15,3)

array([ 1,  4,  7, 10, 13])

In [ ]:
#22.
def evenly_spaced_array(start,stop,space):
  return np.linspace(start,stop,space)


In [ ]:
evenly_spaced_array(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
#23.
def logrithmically_spaced(start,stop,num):
  return np.logspace(start,stop,num)

In [ ]:
logrithmically_spaced(0,3,5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [ ]:
import pandas as pd
#24.
data = np.random.randint(1,101,size = (5,3))

df = pd.DataFrame(data)

In [ ]:
print(df)

    0   1   2
0  79  35  82
1   8  43  27
2  40  43  29
3  84  31   1
4  85  16  17


In [ ]:
#25.

def replace_negative_with_zero(df, column_name):
  df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
  return df

In [ ]:
data = {'A': [1, -2, 3, -4],
        'B': [-5, 6, -7, 8]}

df = pd.DataFrame(data)
replace_negative_with_zero(df,"B")

A  B
0  1  0
1 -2  6
2  3  0
3 -4  8

In [ ]:
#26.
arr = np.array([10,20,30,40,50])
arr[2]

30

In [ ]:
#27.
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
arr_2d[1,2]

6

In [ ]:
#28.
arr = np.array([3,8,2,10,5,7])
arr[arr>5]

array([ 8, 10,  7])

In [ ]:
#29.
arr = [1,2,3,4,5,6,7,8,9]
arr[2:5]

[3, 4, 5]

In [ ]:
#30.
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
sub_array = arr2d[0:2,1:3]

In [ ]:
sub_array

array([[2, 3],
       [5, 6]])

In [ ]:
#31.
def extract_element(arr, indices):
    result = np.empty((indices.shape[0]), dtype=arr.dtype)
    for i in range(indices.shape[0]):
        result[i] = arr[indices[i][0], indices[i][1]]
    return result

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
indices = np.array([[0,1],[1,2],[2,0]])
extract_element(arr,indices)

array([2, 6, 7])

In [ ]:
#32.
def filter_greter_than(arr,thresold):
  return arr[arr>thresold]
arr = np.array([1,2,3,4,5,6,7,8,9])
filter_greter_than(arr,5)

array([6, 7, 8, 9])

In [ ]:
#33.
def extract_element_3d(arr, indices):
    result = np.empty((indices.shape[0]), dtype=arr.dtype)
    for i in range(indices.shape[0]):
        result[i] = arr[indices[i][0], indices[i][1], indices[i][2]]
    return result

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
indices = np.array([[0, 1, 0], [1, 0, 2]])
extract_element_3d(arr,indices)

array([4, 9])

In [ ]:
#34.
def filter_arr(arr,condition1,condition2):
    filtered_arr =  arr[(condition1) & (condition2)]
    return filtered_arr

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = arr > 3
condition2 = arr < 8
filtered_arr = filter_arr(arr, condition1, condition2)
print(filtered_arr)

[4 5 6 7]


In [ ]:
#35.
def extract_row_column(arr,row_indices,col_indices):
  result = np.empty((row_indices.shape[0]), dtype=arr.dtype)
  for i in range(row_indices.shape[0]):
      result[i] = arr[row_indices[i], col_indices[i]]
  return result

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_indices = np.array([0,1,2])
col_indices = np.array([1,2,0])
extract_row_column(arr,row_indices,col_indices)

array([2, 6, 7])

In [ ]:
#36.
arr = np.random.randint(1,10,size = (3,3))
arr

array([[7, 9, 5],
       [4, 9, 7],
       [6, 4, 8]])

In [ ]:
arr+5

array([[12, 14, 10],
       [ 9, 14, 12],
       [11,  9, 13]])

In [ ]:
#37.
arr1 = np.random.randint(1,5,(3,1))
arr2 = np.random.randint(1,10,(3,4))
arr1

array([[2],
       [3],
       [4]])

In [ ]:
arr2

array([[5, 7, 2, 7],
       [1, 9, 7, 6],
       [4, 4, 6, 7]])

In [ ]:
np.multiply(arr1,arr2)

array([[ 4, 10,  8, 18],
       [27, 27, 18, 27],
       [12,  8, 36, 12]])

In [ ]:
#38.
arr1 = np.random.randint(1,5,(1,4))
arr2 = np.random.randint(1,10,(4,3))
arr1

array([[1, 3, 3, 3]])

In [ ]:
arr2

array([[2, 8, 5],
       [4, 2, 1],
       [5, 9, 1],
       [5, 7, 9]])

In [ ]:
arr1_reshaped = arr1.reshape(-1, 1)

result = arr2 + arr1_reshaped
print(result)

[[ 3  9  6]
 [ 7  5  4]
 [ 8 12  4]
 [ 8 10 12]]


In [ ]:
#39.
arr1 = np.random.randint(1,10,(3,1))
arr2 = np.random.randint(1,5,(1,3))
# add array using brodcasting
np.add(arr1,arr2)

array([[ 3,  6,  3],
       [ 3,  6,  3],
       [ 9, 12,  9]])

In [ ]:
#40

arr1 = np.random.randint(1, 10, (2, 3))
arr2 = np.random.randint(1, 15, (2, 2))

# Reshape arr2 to match the shape of arr1
reshaped_arr2 = arr2.reshape(2, 2, 1)

# Perform multiplication using broadcasting
result = reshaped_arr2 * arr1

print(result)

[[[  5   4   5]
  [ 18   8   4]]

 [[ 50  40  50]
  [117  52  26]]]


In [ ]:
#41
arr = np.array([[1,2,3],[4,5,6]])
np.mean(arr,axis = 1)


array([2., 5.])

In [ ]:
#42
arr = np.array([[1,2,3],[4,5,6]])
np.max(arr,axis = 1)

array([3, 6])

In [ ]:
#43
arr = np.array([[1,2,3],[4,5,6]])
np.argmax(arr,axis = 0)

array([1, 1, 1])

In [ ]:
#44
arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr):
  result = np.zeros_like(arr)
  for i in range(arr.shape[0]):
    for j in range(1, arr.shape[1]):
      result[i, j] = result[i, j - 1] + arr[i, j]
  return result

moving_sum_array = moving_sum(arr)
print(moving_sum_array)

[[ 0  2  5]
 [ 0  5 11]]


In [ ]:
#45
arr = np.array([[1,2,3],[4,5,6]])
arr%2==0

array([[False,  True, False],
       [ True, False,  True]])

In [ ]:
#46
original_array = np.array([1,2,3,4,5,6])
m = 2
n = 3
reshaped_matrix = np.reshape(original_array,(m,n))
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
#47
input_matrix = np.array([[1,2,3],[4,5,6]])

def flatten_array(input_matrix):
  return input_matrix.flatten()

flatten_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#48
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

def concat_arrays(arr1,arr2,axis):
  return np.concatenate((arr1,arr2),axis = axis)

concat_arrays(arr1,arr2,0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
concat_arrays(arr1,arr2,1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#49
orginal_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
def split_array_into_subarrays(orginal_array, indices_or_sections, axis=0):
  return np.split(orginal_array,indices_or_sections, axis=axis)

split_array_into_subarrays(orginal_array,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
#50
original_array = np.array([1,2,3,4,5])
indices_to_insert = [2,4]
values_to_insert = [10,11]
indices_to_delete = [1,3]

In [ ]:
def insert_delete_indicies(original_array,indices_to_insert,values_to_insert,indices_to_delete):
   array_with_insertation = np.insert(original_array,indices_to_insert,values_to_insert)
   result_array = np.delete(array_with_insertation,indices_to_delete)
   return result_array

In [ ]:
result = insert_delete_indicies(original_array,indices_to_insert,values_to_insert,indices_to_delete)
print(result)

[ 1 10  4 11  5]


In [ ]:
#51
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))
print(arr1)
print(arr2)
addition = np.add(arr1,arr2)
print(addition)

[[8 3 6]
 [7 2 6]
 [7 6 7]]
[[2 6 8]
 [8 9 1]
 [4 2 4]]
[[10  9 14]
 [15 11  7]
 [11  8 11]]


In [ ]:
#52
arr1 = np.array([10,9,8,7,6,5,4,3,2,1])
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
substract = arr2-arr1
print(substract)



[-9 -7 -5 -3 -1  1  3  5  7  9]


In [ ]:
#53
arr1 = np.random.randint(1,5,(3,2))
arr2 = np.random.randint(1,5,(3,2))
print(arr1)
print(arr2)
multiplication = arr1*arr2
print(multiplication)

[[4 4]
 [4 3]
 [1 3]]
[[3 2]
 [4 2]
 [2 1]]
[[12  8]
 [16  6]
 [ 2  3]]


In [ ]:
#54
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([1,2,3,4,5])
divison = arr1 /arr2
print(divison)

[2. 2. 2. 2. 2.]


In [ ]:
#55
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
result = np.power(arr1,arr2)
print(result)

[ 1 16 27 16  5]


In [ ]:
#56
arr = np.array(['hello','world','hello','numpy','hello'])
def count_substr(str,substr):
  count = 0
  for i in str:
    if i == substr:
      count += 1
  return count


In [ ]:
count_substr(arr,'hello')

3

In [ ]:
#57
arr = np.array(['Hello','World','OpenAI','GPT'])
def extract_upper(arr):
  result = []
  for word in arr:
    for char in word:
      if char.isupper():
        result.append(char)
  return result

In [ ]:
extract_upper(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

In [ ]:
#58
arr = np.array(['apple','banana','grapes','pinapple'])

def replace_substr(arr,old_substr,new_substr):
  return np.char.replace(arr,old_substr,new_substr)




In [ ]:
replace_substr(arr,'apple','orange')

array(['orange', 'banana', 'grapes', 'pinorange'], dtype='<U9')

In [ ]:
#59
arr1 = np.array(['Hello','World'])
arr2 = np.array(['Open','AI'])

def concat_arrays(arr1,arr2):
    return np.char.add(arr1,arr2)


In [ ]:
concat_arrays(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [ ]:
#60
arr = np.array(['apple','banana','grape','pineapple'])


def len_longest_eliment(arr):
  longest_length = 0
  for i in arr:
    if len(i) > longest_length:
      longest_length = len(i)
  return longest_length



In [ ]:
len_longest_eliment(arr)


9

In [ ]:
#61
dataset = np.random.randint(1,1000,(100))

print("mean:",np.mean(dataset))
print("median:",np.median(dataset))
print("variance:",np.var(dataset))
print("standard deviation:",np.std(dataset))



mean: 495.11
median: 514.5
variance: 71391.5379
standard deviation: 267.19194954189766


In [ ]:
#62
dataset = np.random.randint(1,100,(50))
dataset


array([84, 12, 90, 80, 53, 89, 53, 53,  5, 95, 63, 24, 37, 21, 11, 63, 68,
       53, 25, 31, 99,  2,  3, 81, 74, 73, 69, 38, 44, 86, 78, 55, 28, 97,
       81, 10, 15, 26, 39, 39, 33, 59, 26, 43, 83, 38, 53, 22, 24, 27])

In [ ]:
print('25 percentile is',np.percentile(dataset,25))
print('75 percentile is',np.percentile(dataset,75))


25 percentile is 26.0
75 percentile is 73.75


In [ ]:
#63
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,4,6,8,10])

corelation_coeffecient = np.corrcoef(arr1,arr2)
print("corelation coefecient is",corelation_coeffecient)


corelation coefecient is [[1. 1.]
 [1. 1.]]


In [ ]:
#64
mat1 = np.random.randint(1,10,(3,3))
mat2 = np.random.randint(1,10,(3,3))
print(mat1)
print(mat2)
print('matrix multiplication is')
np.dot(mat1,mat2)

[[9 4 8]
 [5 6 7]
 [4 7 1]]
[[1 3 6]
 [7 5 5]
 [3 9 9]]
matrix multiplication is


array([[ 61, 119, 146],
       [ 68, 108, 123],
       [ 56,  56,  68]])

In [ ]:
#65
arr = np.random.randint(1,1000,(50))
arr

array([851, 492, 890, 190, 275, 599,  53,  44, 453, 378, 953, 130, 423,
       304, 800, 185, 960, 409, 335, 781, 601, 221, 734,  64,  62, 256,
       770, 108, 706, 849,  39, 909, 175, 292, 391, 296, 684,  35, 362,
       877, 337, 714, 501, 138, 351, 872, 730, 932, 860,  63])

In [ ]:
print('10th percentile is',np.percentile(arr,10))
print('50th percentile is',np.percentile(arr,50))
print('90th percentile is',np.percentile(arr,90))
print('first quartile is',np.percentile(arr,25))
print('third quartile is',np.percentile(arr,75))

10th percentile is 62.9
50th percentile is 400.0
90th percentile is 878.3000000000001
first quartile is 197.75
third quartile is 761.0


In [ ]:
#66
arr = np.array([2,3,4,5,6,7,8])
np.where(arr == 4)

(array([2]),)

In [ ]:
#67
arr = np.random.randint(1,15,(15))
arr

array([ 7,  5,  1,  4,  1,  9,  3, 11, 13, 12,  5,  2,  7, 10,  2])

In [ ]:
sorted(arr)

[1, 1, 2, 2, 3, 4, 5, 5, 7, 7, 9, 10, 11, 12, 13]

In [ ]:
#68
arr = np.array([12,25,6,42,8,30])
arr[arr>20]

array([25, 42, 30])

In [ ]:
#69
arr = np.array([1,5,8,12,15])
arr[arr%3==0]

array([12, 15])

In [ ]:
#70
arr = np.array([10,20,30,40,50])
arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])

In [ ]:
#71
arr = np.array([1,2,3])
print(arr.dtype.byteorder)

=


In [ ]:
#72
arr = np.array([1,2,3],dtype = np.int32)
print(arr.byteswap())



[16777216 33554432 50331648]


In [ ]:
#73
arr = np.array([1,2,3],dtype=np.int32)
arr_swapped = arr.newbyteorder()
print(arr_swapped.dtype.byteorder)

>


In [ ]:
#74

arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is needed based on system endianness
if sys.byteorder == 'little':
    arr_swapped = arr.newbyteorder('>')  # Swap to big-endian if system is little-endian
elif sys.byteorder == 'big':
    arr_swapped = arr.newbyteorder('<')  # Swap to little-endian if system is big-endian

# Print the byte order of the swapped array
print(arr_swapped.dtype.byteorder)


>


In [ ]:
import sys
#75
arr = np.array([1, 2, 3], dtype=np.int32)

native_byteorder = sys.byteorder
array_byteorder = arr.dtype.byteorder

if native_byteorder != array_byteorder:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")

Byte swapping is necessary.


In [ ]:
#76
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

copy_arr = np.copy(arr1)
# Modifying copy_arr
copy_arr[3] = 30
print(copy_arr)
print(arr1)

[ 1  2  3 30  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# it is not effectin arr1 when i am modifying copy_arr

In [ ]:
#77
# original matrix
matrix = np.random.randint(1, 10, (3, 3))
print("Original matrix:\n", matrix)

#  a slice  of the matrix
view_slice = matrix[1:, 1:]
print("\nSlice view:\n", view_slice)

# Modify an element in the slice view
view_slice[0, 0] = 999
print("\nSlice view after modification:\n", view_slice)

# Check if the original matrix is altered
print("\nOriginal matrix after modification of slice:\n", matrix)


Original matrix:
 [[5 9 1]
 [8 1 1]
 [8 6 3]]

Slice view:
 [[1 1]
 [6 3]]

Slice view after modification:
 [[999   1]
 [  6   3]]

Original matrix after modification of slice:
 [[  5   9   1]
 [  8 999   1]
 [  8   6   3]]


In [ ]:
# it is effecting the orginal array


In [ ]:
#78
# original array
array_a = np.arange(1, 13).reshape(4, 3)
print("Original array:\n", array_a)

#  a slice of the array
view_b = array_a[1:3, :]
print("\nSlice view:\n", view_b)

# Broadcast addition of 5 to the slice view
view_b += 5
print("\nSlice view after broadcasting:\n", view_b)

# Check if the original array is altered
print("\nOriginal array after modification of slice:\n", array_a)

Original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice view:
 [[4 5 6]
 [7 8 9]]

Slice view after broadcasting:
 [[ 9 10 11]
 [12 13 14]]

Original array after modification of slice:
 [[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]


In [ ]:
# it is also effecting the original array as well

In [ ]:
#79
orig_array = np.arange(1,9).reshape(2,4)
print('original_array:\n',orig_array)
# creating reshaped_view
reshaped_view = orig_array.reshape(4,2)
print('\noriginal_array:\n',reshaped_view)

#Modifying the reshaped_view
reshaped_view[1,1] = 34
print('\nModified reshaped_view:\n',reshaped_view)

#Check if the original array is altered
print('\nOriginal array after modification of reshaped_view:\n',orig_array)

original_array:
 [[1 2 3 4]
 [5 6 7 8]]

original_array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified reshaped_view:
 [[ 1  2]
 [ 3 34]
 [ 5  6]
 [ 7  8]]

Original array after modification of reshaped_view:
 [[ 1  2  3 34]
 [ 5  6  7  8]]


In [ ]:
# Yes , it is reflecting in the original array

In [ ]:
#80
data = np.random.randint(1,20,(3,4))
print(data)
# creating a copy of data > 5
data_copy = np.copy(data[data>5])
print("\ncopied data from data:\n",data_copy)
# modifying the data_copy
data_copy[0] = 100
print("\nmodified data_copy:\n",data_copy)
# Check if the original array is altered
print("\nOriginal array after modification of data_copy:\n",data)



[[11  6  7 13]
 [ 6 11 16  9]
 [18  4 15 11]]

copied data from data:
 [11  6  7 13  6 11 16  9 18 15 11]

modified data_copy:
 [100   6   7  13   6  11  16   9  18  15  11]

Original array after modification of data_copy:
 [[11  6  7 13]
 [ 6 11 16  9]
 [18  4 15 11]]


In [ ]:
# No, it is not effecting the original array

In [ ]:
#81
A = np.array([[1, 2], [3, 4]])
B = np.array([[5,6],[7,5]])
addition = A+B
print('Addition is:\n',addition)
substraction = A-B
print('Substraction is:\n',substraction)

Addition is:
 [[ 6  8]
 [10  9]]
Substraction is:
 [[-4 -4]
 [-4 -1]]


In [ ]:
#82
C = np.random.randint(1,15,(3,2))
D = np.random.randint(1,15,(2,4))
print(C)
print(D)
multiplication = C.dot(D)
print('\nMatrix multiplication is:\n',multiplication)

[[ 7 14]
 [ 7  6]
 [ 4  9]]
[[10  8  3 14]
 [ 5  6  5  2]]

Matrix multiplication is:
 [[140 140  91 126]
 [100  92  51 110]
 [ 85  86  57  74]]


In [ ]:
#83
E = np.random.randint(1,17,(3,2))
print(E)
transpose = E.T
print('\nTranspose is:\n',transpose)


[[13 16]
 [ 4  1]
 [ 5 11]]

Transpose is:
 [[13  4  5]
 [16  1 11]]


In [ ]:
#84
F = np.random.randint(1,15,(3,3))
print(F)
det_f = np.linalg.det(F)
print('\nDeterminant is:\n',det_f)

[[ 1 13 12]
 [ 1  1  6]
 [ 5  3 13]]

Determinant is:
 192.0


In [ ]:
#85
G = np.random.randint(1,15,(3,3))
print(G)
inv_g = np.linalg.inv(G)
print('\nInverse is:\n',inv_g)

[[10  4 12]
 [ 8  6 13]
 [12 14  1]]

Inverse is:
 [[ 0.25581395 -0.23837209  0.02906977]
 [-0.21511628  0.19476744  0.0494186 ]
 [-0.05813953  0.13372093 -0.04069767]]
